image: "rust:latest"
before_script:
  - rustup component add rustfmt-preview
  - rustup component add clippy-preview

cache:
  key: "$CI_JOB_NAME"
  untracked: true
  paths:
  - $HOME/.cargo/
  - target/

test:cargo:
  script:
  - rustc --version && cargo --version
  - cargo test --all --verbose

variables:
  RUST_BACKTRACE: "1"

lint:rustfmt:
  script:
    - cargo fmt --all -- --check

lint:clippy:
  allow_failure: true
  script:
    - cargo clippy --all-targets --all-features -- -D warnings
