#!/bin/sh
#
# Usage example:
#
#     ./tools/report/weak-scaling monkey.meshb spike,1000 -a random,2 -a fm,0.04

set -e

. "$(dirname "$0")"/common.sh
cargo build -p coupe-tools --bins --release
PATH="$TARGET_DIR/release:$PATH"
TARGET_DIR=./target

MESH_FILE=$1
shift

WEIGHT_DIST=$1
shift

tmp_mesh=$(echo 'maketemp(/dev/shm/weak-scaling.XXXXXX)' | m4)
tmp_weights="$tmp_mesh".weights
trap "rm -f $tmp_mesh $tmp_weights" 0 2 3 15

bench_name=$(basename "$tmp_mesh" | tr '.' ';')
for arg in $@
do
	if [ "$arg" != "${arg#-}" ]
	then continue
	fi
	bench_name="$bench_name;$arg"
done

max_threads=$(grep -c ^processor /proc/cpuinfo)
RAYON_NUM_THREADS=1

mesh_dup() {
	n=$1

	say dedup "$MESH_FILE"
	rm "$tmp_mesh"
	mesh-dup -n "$n" <"$MESH_FILE" >"$tmp_mesh"
}

weight_gen() {
	say weight-gen "$tmp_weights"
	weight-gen --distribution "$WEIGHT_DIST" <"$tmp_mesh" >"$tmp_weights"
}

part_bench() {
	say bench "$RAYON_NUM_THREADS threads"
	part-bench --mesh "$tmp_mesh" \
	           --weights "$tmp_weights" \
	           --sample-size 10 \
	           --edge-weights linear \
	           $@

	cd "$TARGET_DIR/criterion/$bench_name"

	dir="refine=$RAYON_NUM_THREADS"
	mkdir "$dir"
	mv base new "$dir"
	cp -r report "$dir"

	cd - >/dev/null
}

ln -sf "$(realpath "$MESH_FILE")" "$tmp_mesh"
weight_gen

while true
do
	part_bench $@

	RAYON_NUM_THREADS=$(( $RAYON_NUM_THREADS * 2 ))
	if [ $RAYON_NUM_THREADS -gt $max_threads ]
	then
		break
	fi

	mesh_dup "$RAYON_NUM_THREADS"
	weight_gen

	say sleep "Cooling CPUs down for 4s..."
	sleep 4
done
