[package]
name = "examples"
version = "0.1.0"
authors = [
    "Armand Touminet <armand.touminet@protonmail.com>", 
    "Cédric Chevalier", 
    "Sébastien Morais"
]
publish = false
autobins = false

[[bin]]
name = "balanced_k_means"

[[bin]]
name = "rcb_2d"

[[bin]]
name = "rcb_3d"

[[bin]]
name = "rib_2d"

[[bin]]
name = "rib_3d"

[[bin]]
name = "multi_jagged"

[[bin]]
name = "hilbert_curve"

[[bin]]
name = "simplified_k_means"

[[bin]]
name = "xyz_mesh"

[dependencies]
coupe = { version = "0.1.0", path = "../" }
clap = { version = "2.32.0", features = ["yaml"]}
failure = "0.1.3"
gnuplot = "0.0.26"
itertools = "0.7.8"
rayon = "1.0.3"
rand = "0.5.5"
snowflake = "1.2"

mesh_io = { path = "../../mesh_io" }
