[package]
name = "examples"
version = "0.1.0"
authors = [
    "Armand Touminet <armand.touminet@protonmail.com>", 
    "Cédric Chevalier", 
    "Sébastien Morais"
]
publish = false

[dependencies]
coupe = { path = "../" }
clap = { version = "2.32.0", features = ["yaml"]}
gnuplot = "0.0.26"
itertools = "0.7.8"
rand = "0.5.5"
snowflake = "1.2"

